# ===== Database =====
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_prep
spring.datasource.username=postgres
spring.datasource.password=harshi
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== JWT =====
jwt.secret=MySuperSecretKeyForJWTSigning2024!!

# ===== Groq AI =====
groq.api.key=${GROQ_API_KEY}

# ===== Server =====
server.port=8080
